# Generated by Django 4.0.3 on 2022-03-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_date_created_employee_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
